name: Build LaTeX Hymnbook

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install TinyTeX
      run: |
        wget -qO- https://yihui.org/tinytex/install-unx.sh | sh
        echo "$HOME/bin" >> $GITHUB_PATH
        ~/.TinyTeX/bin/*/tlmgr path add

    - name: Install required LaTeX packages
      run: |
        tlmgr install latexmk collection-latexrecommended \
          collection-latexextra collection-fontsrecommended

    - name: Compile LaTeX document
      run: |
        latexmk -pdf hymnbook.tex

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: hymnbook-pdf
        path: hymnbook.pdf
