name: Build LaTeX Hymnbook

on:
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Tectonic
      uses: actions-rs/tectonic@v1

    - name: Compile LaTeX document
      run: |
        tectonic hymnbook.tex --print --keep-logs --keep-intermediates

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: hymnbook-pdf
        path: hymnbook.pdf
