name: Build LaTeX Hymnbook

on:
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install TeX Live (minimal)
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-latex-recommended \
          texlive-latex-extra texlive-fonts-recommended latexmk

    - name: Compile LaTeX document
      run: |
        latexmk -pdf hymnbook.tex
        
    - name: Auto Commit PDFs
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Compiled LaTeX files with View and Print versions"
        push_options: '--force'
        file_pattern: '*.pdf'
        

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: hymnbook-pdf
        path: hymnbook.pdf
