name: Compile LilyPond

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  compile:
    runs-on: ubuntu-latest # Or macos-latest if you prefer

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up LilyPond
      # This action sets up LilyPond on the runner.
      # You can specify a version if needed, e.g., '2.24.0'.
      # Check the action's marketplace page for available versions.
      uses: zamband/setup-lilypond@v1
      with:
        lilypond-version: '2.24.2' # Specify your desired LilyPond version

    - name: Compile OnePage.ly
      run: |
        lilypond OnePage.ly

    - name: Upload compiled PDF
      uses: actions/upload-artifact@v4
      with:
        name: OnePage-pdf
        path: OnePage.pdf # The compiled PDF file
