name: Compile LilyPond

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  compile:
    runs-on: ubuntu-latest # Run on an Ubuntu virtual machine

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install LilyPond
      run: |
        sudo apt-get update
        sudo apt-get install -y lilypond

    - name: Compile OnePage.ly from OnePage folder
      run: |
        cd OnePage/ # Change directory to the OnePage folder
        lilypond OnePage.ly

    - name: Upload compiled PDF
      uses: actions/upload-artifact@v4
      with:
        name: OnePage-pdf
        path: OnePage/OnePage.pdf # The compiled PDF file will be in the OnePage folder
