name: Compile LilyPond

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile OnePage.ly using LilyPond Docker image
      run: |
        # Define the LilyPond version to use.
        # You can find available versions on Docker Hub: https://hub.docker.com/r/lilypond/lilypond/tags
        LILYPOND_VERSION="2.24.3" # Or 'latest', '2.25.x', etc.

        # Run the LilyPond Docker image
        # -v ${{ github.workspace }}:/data mounts your repository to /data inside the container
        # lilypond /data/OnePage/OnePage.ly executes lilypond on your file
        docker run --rm \
          -v "${{ github.workspace }}:/data" \
          lilypond/lilypond:${LILYPOND_VERSION} \
          /data/OnePage/OnePage.ly
      # The working directory for this step is the repository root by default.
      # The output PDF will be generated in OnePage/ within the mounted volume.

    - name: Upload compiled PDF
      uses: actions/upload-artifact@v4
      with:
        name: OnePage-pdf
        # The PDF will be generated directly in the OnePage/ folder relative to the workspace.
        path: OnePage/OnePage.pdf
