name: Compile LilyPond

on:
  workflow_dispatch: # Allows manual triggering of the workflow from the GitHub UI

jobs:
  compile:
    runs-on: ubuntu-latest # Run on an Ubuntu virtual machine

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install LilyPond and font utilities
      run: |
        sudo apt-get update
        sudo apt-get install -y lilypond fontconfig # fontconfig provides fc-cache

    - name: Install Custom Font (Nyala)
      run: |
        mkdir -p ~/.fonts # Create a fonts directory in the home folder if it doesn't exist
        cp ${{ github.workspace }}/fonts/Nyala.ttf ~/.fonts/ # Copy the font file
        fc-cache -fv # Rebuild the font cache. This makes the font available to applications.

    - name: Update LilyPond files with convert-ly
      run: |
        find . -name "*.ly" | xargs -r -n 1 convert-ly -e

    - name: Compile OnePage.ly from OnePage folder
      run: |
        cd OnePage/ # Change directory to the OnePage folder
        lilypond OnePage.ly

    - name: Upload compiled PDF
      uses: actions/upload-artifact@v4
      with:
          name: OnePage-pdf
          path: OnePage/OnePage.pdf # The compiled PDF file will be in the OnePage folder
